package com.base.model;

import java.util.Date;

public class UserVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.user_passs
     *
     * @mbg.generated
     */
    private String userPasss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.actor
     *
     * @mbg.generated
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.cteated_time
     *
     * @mbg.generated
     */
    private Date cteatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.modifyed_time
     *
     * @mbg.generated
     */
    private Date modifyedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.user_id
     *
     * @return the value of test_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.user_id
     *
     * @param userId the value for test_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.user_name
     *
     * @return the value of test_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.user_name
     *
     * @param userName the value for test_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.user_passs
     *
     * @return the value of test_user.user_passs
     *
     * @mbg.generated
     */
    public String getUserPasss() {
        return userPasss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.user_passs
     *
     * @param userPasss the value for test_user.user_passs
     *
     * @mbg.generated
     */
    public void setUserPasss(String userPasss) {
        this.userPasss = userPasss == null ? null : userPasss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.actor
     *
     * @return the value of test_user.actor
     *
     * @mbg.generated
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.actor
     *
     * @param actor the value for test_user.actor
     *
     * @mbg.generated
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.cteated_time
     *
     * @return the value of test_user.cteated_time
     *
     * @mbg.generated
     */
    public Date getCteatedTime() {
        return cteatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.cteated_time
     *
     * @param cteatedTime the value for test_user.cteated_time
     *
     * @mbg.generated
     */
    public void setCteatedTime(Date cteatedTime) {
        this.cteatedTime = cteatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.modifyed_time
     *
     * @return the value of test_user.modifyed_time
     *
     * @mbg.generated
     */
    public Date getModifyedTime() {
        return modifyedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.modifyed_time
     *
     * @param modifyedTime the value for test_user.modifyed_time
     *
     * @mbg.generated
     */
    public void setModifyedTime(Date modifyedTime) {
        this.modifyedTime = modifyedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.description
     *
     * @return the value of test_user.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.description
     *
     * @param description the value for test_user.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}